### ISSUE TITLE
HMS production replay broken, BCM detector outside hms_shared.h

### ISSUE THREAD

**Issue by mrcmor100** [JeffersonLab/hallc_replay_XEM#6]
https://github.com/JeffersonLab/hallc_replay_XEM/blob/d675f0e9f272c56c08737b9b23b0463ac1e77495/SCRIPTS/HMS/PRODUCTION/replay_production_hms.C#L34
Extra BCM detector module instantiated.  hms_shared already implements the BCM detector.  This will attempt to load a BCM PARAM file even if one does not exist.  This causes hcana to crash.

**Comment by gaskelld** [comment]
I added this to the online - the BCMs weren't showing up in the T tree even even when a calibration file was present. This was the only way I could get it to work.

**Comment by ccotton98** [comment]
This issue was resolved by pull request #8 and can be closed.

**Comment by ccotton98** [comment]
rootlogon.C was starting root in the wrong directory, so changes in the current directory were not having any impact. This was fixed. The bug in hms_shared.C that caused BCMs to never be loaded has been fixed. Dave's workaround to this bug in replay_production_hms.C was removed.
